---
1st_line: "&l&a[&bSW&a]"
2nd_line: "&l&e{SWNAME}"
CONFIG_VERSION: 0.7dev
always.spawn.in.defaultLevel: true
banned.commands.while.in.game: 
  - /hub
  - /lobby
  - /spawn
  - /tpa
  - /tp
  - /tpaccept
  - /back
  - /home
  - /f
  - /kill
chest.refill: true
chest.refill.rate: 240
clear.effects.on.arena.join: true
clear.effects.on.respawn&join: false
clear.inventory.on.arena.join: true
clear.inventory.on.respawn&join: false
damage.cancelled.causes: 
  - 0
  - 3
  - 4
  - 8
  - 12
  - 15
death.spectator: true
drops.on.death: false
join.health: 20
join.max.health: 20
knockBack.follow.sign.direction: false
knockBack.intensity: 2
knockBack.radius.from.sign: 1
needed.players.to.run.countdown: 2
no.pvp.countdown: 0
player.drop.item: true
reward.command: /
reward.value: 100
reward.winning.players: false
sign.knockBack: true
sign.tick: false
spectator.quit.item: "120:0"
start.when.full: true
world.compress.tar: false
world.generator.air: true
world.reset.from.tar: true
...
